version: 2
updates:
  - package-ecosystem: gomod
    directory: /
    schedule:
      interval: weekly
    groups:
      charm-tui:
        patterns:
          - "github.com/charmbracelet/*"
          - "github.com/muesli/*"
      golang-org:
        patterns:
          - "golang.org/x/*"
    commit-message:
      prefix: "deps"

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
    commit-message:
      prefix: "ci"
