/**
 * Generates src/components/common/icons.ts from scripts/icon-defs.json.
 *
 * The icon set is VENDORED rather than imported at runtime: the generator reads
 * Lucide's node arrays and writes the SVG children out as markup, so the built
 * library keeps its one runtime dependency beyond Vue and a consuming app needs
 * no icon package of its own.
 *
 * `lucide-vue-next` is therefore a devDependency. Upgrading it and re-running
 * this is how the set is refreshed; the diff on icons.ts is the review.
 *
 * Icons are ISC-licensed; see the attribution written into the generated file.
 *
 * Run: npm run generate-icons
 */
import { readFile, writeFile } from 'node:fs/promises'
import { fileURLToPath } from 'node:url'
import { dirname, resolve } from 'node:path'

const here = dirname(fileURLToPath(import.meta.url))
const root = resolve(here, '..')

const defs = JSON.parse(await readFile(resolve(here, 'icon-defs.json'), 'utf8'))

/**
 * Lucide ships each icon as an ESM module holding a node array of
 * `[tag, attrs]` pairs. Reading that array is what lets a multi-element glyph
 * (a circle plus a path) survive vendoring — the previous hand-drawn set could
 * hold exactly one `<path>` per icon, which most of Lucide does not fit.
 */
async function nodesFor(component) {
  const kebab = component
    .replace(/([a-z])([A-Z])/g, '$1-$2')
    .replace(/([A-Z])([A-Z][a-z])/g, '$1-$2')
    // A trailing digit is its own segment: Table2 is table-2, Maximize2 is
    // maximize-2.
    .replace(/([a-zA-Z])(\d)/g, '$1-$2')
    .toLowerCase()
  // Read the module SOURCE rather than importing it. The node array is the
  // second argument to createLucideIcon, and parsing it out avoids
  // instantiating Vue inside a build script.
  const path = resolve(root, `node_modules/lucide-vue-next/dist/esm/icons/${kebab}.js`)
  const src = await readFile(path, 'utf8').catch(() => null)
  if (src === null) throw new Error(`no Lucide module for ${component} (tried ${kebab})`)
  const body = src.slice(src.indexOf('createLucideIcon('))
  const arr = body.slice(body.indexOf('['), body.lastIndexOf(']') + 1)
  return JSON.parse(
    arr
      // `key` is Lucide's render hint and is not wanted in static markup.
      .replace(/,\s*key:\s*"[^"]*"/g, '')
      .replace(/([{,]\s*)([a-zA-Z][a-zA-Z0-9-]*):/g, '$1"$2":')
      .replace(/,(\s*[}\]])/g, '$1'),
  )
}

function toMarkup(nodes) {
  return nodes
    .map(([tag, attrs]) => {
      const a = Object.entries(attrs)
        .map(([k, v]) => `${k}="${v}"`)
        .join(' ')
      return `<${tag} ${a}/>`
    })
    .join('')
}

const entries = []
for (const [name, component, category, desc] of defs) {
  entries.push({ name, component, category, desc, markup: toMarkup(await nodesFor(component)) })
}

const byCategory = new Map()
for (const e of entries) {
  if (!byCategory.has(e.category)) byCategory.set(e.category, [])
  byCategory.get(e.category).push(e)
}

let out = `/**
 * Code generated by scripts/generate-icons.mjs. DO NOT EDIT.
 * Source: scripts/icon-defs.json. Regenerate with \`npm run generate-icons\`.
 *
 * Icon artwork from Lucide (https://lucide.dev), ISC licensed. The SVG bodies
 * are vendored so this library ships no icon runtime dependency.
 *
 * Every glyph is drawn on Lucide's 24x24 grid and inherits \`currentColor\`,
 * so an icon takes the colour of the text it sits beside in either theme.
 */

/** The SVG children of each glyph, as markup. */
export const icons = {
`
/** A single-quoted TS string literal: backslashes first, then the quotes. */
const quote = (text) => `'${text.replace(/\\/g, '\\\\').replace(/'/g, "\\'")}'`

for (const [category, list] of byCategory) {
  out += `  // ${'\u2500\u2500'} ${category} ${'\u2500'.repeat(Math.max(1, 62 - category.length))}\n`
  for (const e of list) out += `  '${e.name}': ${quote(e.markup)},\n`
}
out += `} as const

/** Every name in the set. A config string is checked against this. */
export type IconName = keyof typeof icons

export const iconNames = Object.keys(icons) as IconName[]

export function isIconName(value: string): value is IconName {
  return Object.prototype.hasOwnProperty.call(icons, value)
}

/** What each glyph depicts, for the catalogue and the picker. */
export const iconMeta: Record<IconName, { category: string; description: string }> = {
`
for (const e of entries) {
  out += `  '${e.name}': { category: '${e.category}', description: ${quote(e.desc)} },\n`
}
out += `}
`

await writeFile(resolve(root, 'src/components/common/icons.ts'), out)
console.log(`Wrote ${entries.length} icons across ${byCategory.size} categories.`)
